apiVersion: monitor.azure.com/v1
kind: Instrumentation
metadata:
  name: default
  namespace: demo-app
spec:
  settings:
    autoInstrumentationPlatforms: # required
      - Java
      - NodeJs
  destination: # required
    applicationInsightsConnectionString: ""
