apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: monitorregistry.azurecr.io/service-a:latest
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_B_URL
          value: "http://service-b.microservices-demo.svc.cluster.local:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

